name: Build Custom Server (All Hands Visible)
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TRAVIS_OS_NAME: linux
      TARGET_OS: windows
      DXSDK_DIR: /tmp/d3d9sdk/
      VCPKG_ROOT: /tmp/vcpkg2
      BUILD_CONFIG: release
      ARCH: win32
      MINGW_LITE_VARIANT: -msvcrt
      VCPKG_TRIPLET: -mingw-static
      EXTRA_CFLAGS: ""
      CC: /usr/local/bin/i686-w64-mingw32-gcc
      CXX: /usr/local/bin/i686-w64-mingw32-g++
      AR: /usr/local/bin/i686-w64-mingw32-gcc-ar
      VCPKG_CACHE_ZIP_URL: https://github.com/edo9300/edopro-vcpkg-cache/releases/latest/download/installed_x86-windows-mingw-static.zip
      PICS_URL: ""
      FIELDS_URL: ""
      COVERS_URL: ""
      DISCORD_APP_ID: ""
      UPDATE_URL: ""
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Install mingw lite toolchain
      shell: bash
      run: ./travis/install_mingw_lite.sh
    - name: Install premake
      shell: bash
      run: ./travis/install-premake5.sh
    - name: Install dependencies
      shell: bash
      run: ./travis/dependencies.sh
    - name: Build
      shell: bash
      run: ./travis/build.sh
    - name: Predeploy
      shell: bash
      run: ./travis/predeploy.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ygoprodll-custom
        path: deploy/
        retention-days: 7
